### ISSUE TITLE
[디자인 상세보기] 최근 업데이트 날자 갱신 기능

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_back#6]
https://github.com/kmu-crc/osd_front/issues/95 이슈에 대응되는 이슈로

디자인 테이블 내 업데이트타임이라는 컬럼의 값을 현재시간(now())계산하여 업데이트한다.

이 요청에 대응되는 기능을 구현한다.

**Comment by opensrcdesign-admin** [comment]
현재 정상동작한다.

하지만, 알아야할 것은 만들어둔 컴포넌트로 하는 것이 아니라,
index.js 에서 바로 처리한다는 점이다.

CORS에 대한 이해가 필요하다.
